---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-foo
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default
  source:
    repoURL: https://github.com/nurembergwitch/argodemo.git
    targetRevision: HEAD # points to the main branch's latest commit
    path: environments/staging/myapp # in the app-of-apps approach the structure is different and more descriptive
  destination: 
    server: https://kubernetes.default.svc
    #namespace: some-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true # if the deployment has an unknown field, it will be rejected
      - CreateNamespace=true # like helm
      - PrunePropagationPolicy=foreground
      - PruneLast=true