apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonserver
  template:
    metadata:
      labels:
        app: pythonserver
    spec:
      containers:
      - name: pythonserver
        image: dirt1992/pythonserverblank:v0.1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources: {}
